spring:
  profiles: dev
  datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: ${PSD2_DB_URL}
    username: ${PSD2_DB_USER}
    password: ${PSD2_DB_PASS}
    initialize: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  data:
    rest:
      max-page-size: 1000
